apiVersion: v1
kind: Service
metadata:
  name: my-landing-page-service
spec:
  type: ClusterIP
  selector:
    app: my-landing-page
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000